### PR TITLE
Fix build for Windows, add aarch64 target for macOS, and general cleanup

### PR DESCRIPTION
**Pull request by segevfiner**
Contributed by courtesy of [swimm.io](https://swimm.io/)

### CODE REVIEW

**Comment by dalance** [comment]
I fixed macOS CI failure.
Could you rebase?

**Comment by segevfiner** [comment]
> I fixed macOS CI failure. Could you rebase?

Rebased

**Comment by dalance** [comment]
Thanks.
I'll merge this because the remaining failure is caused by test issue.

**Comment by dalance** [comment]
I released v0.3.5.

**Pull request merged**
